user/models.py
from flask_mongoalchemy import MongoAlchemy
from mongoengine import signals

from application import db
from utilities.common import utc_now_ts as now

class User(db.Document):
    username = db.StringField(db_field='u',required=True)
    password = db.StringField(db_field='p',required=True)
    email = db.EmailField(db_field='e',required=True)
    first_name = db.StringField(db_field='fn',max_length=20)
    last_name = db.StringField(db_field='ln',max_length=20)
    created = db.IntField(db_field='cr',default=now())
    bio = db.StringField(db_field='b',max_length=160)
    
 #   @classmethod # decorator used to save the credentials in lowercase
  #  def pre_save(cls, sender, document, **kwargs):
   #     document.username = document.username.lower()
    #    email.username = email.username.lower() 

# signals.pre_save.connect(User.pre_save, sender = User)

user/forms.py
from flask_wtf import Form
from wtforms import validators, StringField, PasswordField
from wtforms.widgets import TextArea
from wtforms.fields.html5 import EmailField
from wtforms.validators import ValidationError
from flask_wtf.file import FileField, FileAllowed
import re
from models import User

# base form used for extending to other forms
class BaseUserForm(Form):
    first_name=StringField('First Name',[validators.Required()])
    last_name=StringField('Last Name',[validators.Required()])
    email=EmailField('Email Address',[validators.Required()])
    username=StringField('username',[validators.Required(),validators.length(min=4,max=25)])
    bio= StringField('bio',[validators.length(max=160)])

# Registration form    
class RegisterForm(BaseUserForm):
    password=PasswordField('New password',[validators.DataRequired(),validators.EqualTo('confirm',message='Passwords must match'),validators.length(min=4,max=25)])
    confirm=PasswordField('Repeat password')
    
    def validate_username(form,field):
        if User.objects.filter(username=field.data).first():
            raise ValidationError("username already exists")
        if not re.match('^[a-zA-Z0-9_-]{4,25}$',field.data):
            raise ValidationError("Invalid Username characters",field.data)
    
    def validate_email(form,field):
        if User.objects.filter(email=field.data).first():
            raise ValidationError("email already taken")

#login form
class LoginForm(Form):
    username=StringField('username',[validators.DataRequired()])
    password=PasswordField('password',[validators.DataRequired(),validators.length(min=4,max=25)])

# Edit form    
class EditForm(BaseUserForm):
    pass        

user/views.py
from flask import Blueprint,render_template,request,redirect,session,url_for,abort
from wtforms.validators import ValidationError
import bcrypt

from user.models import User
from user.forms import RegisterForm, LoginForm, EditForm


user_app = Blueprint('user_app',__name__)


    
@user_app.route('/register',methods=('POST','GET'))
def register():
    form=RegisterForm()
    if form.validate_on_submit():
        hashed_password=bcrypt.hashpw(form.password.data, bcrypt.gensalt(10))
        user = User(username=form.username.data, password=hashed_password, email=form.email.data, first_name=form.first_name.data, last_name=form.last_name.data)
        user.save()
        return 'User registered'
    return render_template('user/register.html',form=form)




@user_app.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    error = None
    
    
    if form.validate_on_submit():
        user = User.objects.filter(username=form.username.data).first()
        if user:
            if bcrypt.hashpw(form.password.data, user.password) == user.password:
                session['username'] = form.username.data
                
            else:
                user = None
        if not user:
            error = 'Incorrect credentials'
    return render_template('user/login.html', form=form, error=error)


@user_app.route('/<username>', methods=('GET', 'POST'))
def profile(username):
    edit_profile = False
    user = User.objects.filter(username=username).first()
    if session.get('username') and user.username == session.get('username'):
        edit_profile = True
    if user:
        return render_template('user/profile.html', user=user, edit_profile=edit_profile)
    else: 
        abort(404)


@user_app.route('/logout', methods=('GET', 'POST'))
def logout():
    session.pop('username')
    return redirect(url_for('user_app.login'))

@user_app.route('/edit', methods=('GET','POST'))
def edit():
    return "Edit Profile"
        



    

templates/_formhelpers.html
{% macro render_field(field) %}

<div class="form-group">

  {{ field.label }}

  {{ field(**kwargs)|safe }}

  {% if field.errors %}

    <ul class="text-danger">

    {% for error in field.errors %}

      <li>{{ error }}</li>

    {% endfor %}

    </ul>

  {% endif %}

</div>

{% endmacro %}

templates/base.html
 <!DOCTYPE html>

<html lang="en">

  <head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %}</title>



    <!-- Bootstrap -->

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">



    {% block header %}{% endblock %}

  </head>

  <body>



    <div class="container">



    {% block content %}{% endblock %}

    

      <div class="col-md-offset-3 col-md-6">

        <hr />

        <footer>

          &copy; copyright 2016 flaskbook

        </footer>

      </div>

      

    </div>



    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

    <script src="https://code.jquery.com/jquery-1.12.1.min.js"></script>

    <!-- Include all compiled plugins (below), or include individual files as needed -->

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    

    {% block end_body_js %}{% endblock %}

    

  </body>

</html>

templates/navbar.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">
                <img alt="flaskbook logo" width="82" height="20" src="{{ url_for('static', filename='assets/flaskbook-logo-sm.png') }}">
            </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                {% if session.username %}
                <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                      @{{ session.username }} <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('user_app.profile', username=session.username) }}">View profile</a></li>
                        <li><a href="{{ url_for('user_app.edit') }}">Edit profile</a></li>
                    </ul>
                </li>
                <li>
                    <a href="{{ url_for('user_app.logout') }}" class="navbar-link">Logout</a></p>
                </li> 
                {% else %}
                <li>
                    <a href="{{ url_for('user_app.login') }}" class="navbar-link">Login</a></p>
                </li>     
                <li>
                    <a href="{{ url_for('user_app.register') }}" class="navbar-link">Register</a></p>
                </li> 
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/user/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">
    
    <h3>User Login</h3>

    {% if error %}
    <div class="alert alert-danger" role="alert">{{ error }}</div>
    {% endif %}

    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('user_app.login')}}" role="form">

      {{ form.hidden_tag() }}

      {{ render_field(form.username, class='form-control') }}
      {{ render_field(form.password, **{"class": "form-control", "aria-described-by": "passwordHelpBlock"}) }}
      
    

      <button type="submit" class="btn btn-default">Login</button>

    </form>

  </div>

</div>
{% endblock %}

templates/user/profile.html
{% extends "base.html" %} 

{% block title %}{{ user.username }} - Profile{% endblock %} 

{% block header %}<link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">{% endblock %}

{% block content %} 

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-3">

    <img class="img-thumbnail" src="//placehold.it/200x200" width="200" heigh="200" alt="{{ user.username }}">

    <h3>{{ user.first_name }} {{ user.last_name }} </h3> 
    <h4><a href="{{ url_for('user_app.profile', username=user.username) }}" />@{{ user.username }}</a></h4>

  </div> <!-- col-md-3 -->
  
  <div class="col-md-9">
    
    <div id="friends-toolbar" class="row">
  
      <div class="btn-toolbar pull-right" role="toolbar" aria-label="friends-toolbar">
        <div class="btn-group" role="group" aria-label="friends-toolbar-buttons">
          {% if edit_profile %}
          <a href="{{ url_for('user_app.edit') }}" role="button" class="btn btn-default">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            Edit profile
          </a>
          {% else %}
          <button type="button" class="btn btn-success">
            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Friends
          </button>
          {% endif %}
        </div>
      </div>
      
    </div> <!-- friends-toolbar -->
    
    <div class="row">
      
      <div class="col-md-9">
        
        <div class="media">
          <div class="media-left">
            <a href="#">
              <img class="media-object" src="//placehold.it/50x50" width="50" heigh="50" alt="{{ user.username }}">
            </a>
          </div>
          <div class="media-body">
            <p>Luis Escobar <a href="#">@luis</a><br />
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis non massa ut ante interdum sagittis. Quisque eu sapien enim. Phasellus sit amet viverra massa, sit amet rhoncus dui. Nam tortor justo, finibus ut gravida et, accumsan ac sapien. Integer nec commodo libero. Nam auctor vestibulum congue. Donec convallis mollis lorem, eu mattis sem luctus in. Curabitur tincidunt odio sit amet nulla fringilla, vel gravida orci aliquam. Donec viverra mollis tortor, a suscipit risus molestie at. Sed ut tincidunt metus. Maecenas nec dignissim velit, eget placerat lectus.
            </p>
          </div>
        </div> <!-- media -->
        
        <div class="media">
          <div class="media-left">
            <a href="#">
              <img class="media-object" src="//placehold.it/50x50" width="50" heigh="50" alt="{{ user.username }}">
            </a>
          </div>
          <div class="media-body">
            <p>Luis Escobar <a href="#">@luis</a><br />
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis non massa ut ante interdum sagittis. Quisque eu sapien enim. Phasellus sit amet viverra massa, sit amet rhoncus dui. Nam tortor justo, finibus ut gravida et, accumsan ac sapien. Integer nec commodo libero. Nam auctor vestibulum congue. Donec convallis mollis lorem, eu mattis sem luctus in. Curabitur tincidunt odio sit amet nulla fringilla, vel gravida orci aliquam. Donec viverra mollis tortor, a suscipit risus molestie at. Sed ut tincidunt metus. Maecenas nec dignissim velit, eget placerat lectus.
            </p>
          </div>
        </div> <!-- media -->
        
      </div> <!-- col-md-9 -->
    
      <div class="col-md-3">

        <h4><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Friends <span class="badge">4</span></h4>
        
        <div class="media">
          <div class="media-left">
            <a href="#">
              <img class="media-object" src="//placehold.it/50x50" width="50" heigh="50" alt="{{ user.username }}">
            </a>
          </div>
          <div class="media-body">
            <p>Luis Escobar<br />
              <a href="#">@luis</a>
            </p>
          </div>
        </div> <!-- media -->

        <div class="media">
          <div class="media-left">
            <a href="#">
              <img class="media-object" src="//placehold.it/50x50" width="50" heigh="50" alt="{{ user.username }}">
            </a>
          </div>
          <div class="media-body">
            <p>Luis Escobar<br />
              <a href="#">@luis</a>
            </p>
          </div>
        </div> <!-- media -->

      </div> <!-- col-md-3 -->
      
    </div> <!-- row -->
    
  </div> <!-- col-md-9 -->

</div>
{% endblock %}

templates/user/register.html
{% extends "base.html" %}



{% block title %}Registration{% endblock %}



{% block content %}





<div class="row">



  <div class="col-md-offset-3 col-md-6">



    <h3>Registration</h3>



    {% from "_formhelpers.html" import render_field %}

    <form method="POST" action="{{ url_for('.register')}}" role="form">



      {{ form.hidden_tag() }}



      {{ render_field(form.first_name, class='form-control') }}

      {{ render_field(form.last_name, class='form-control') }}

      

      {{ render_field(form.username, class='form-control') }}

      {{ render_field(form.email, class='form-control') }}

      

      {{ render_field(form.password, class='form-control') }}

      {{ render_field(form.confirm, class='form-control') }}



      <button type="submit" class="btn btn-default">Register</button>



    </form>



  </div>



</div>

{% endblock %}